<?php 
    $this->headTitle("Direct Referral Bonus");
    $this->headLink()->prependStylesheet($this->basePath('/assets/aim-world/css/style.css'));
?>
<div class="container">
    <div class="col-md-10 col-sm-10">
        <section id="overview">
            <h1>Overview</h1>
            <p>
                In incididunt echo park, officia deserunt mcsweeney's proident master cleanse thundercats sapiente veniam. Excepteur VHS elit, proident shoreditch +1 biodiesel laborum craft beer. Single-origin coffee wayfarers irure four loko, cupidatat terry richardson master cleanse. Assumenda you probably haven't heard of them art party fanny pack, tattooed nulla cardigan tempor ad. Proident wolf nesciunt sartorial keffiyeh eu banh mi sustainable. Elit wolf voluptate, lo-fi ea portland before they sold out four loko. Locavore enim nostrud mlkshk brooklyn nesciunt.
            </p>
        </section>        
    </div>
    <div class="col-md-2 col-sm-2">
        <div class="col-md-2 col-sm-2" >
            <ul class="nav nav-stacked affix" id="side-nav">
                <li><a href="#overview">Overview</a></li>                
            </ul>
        </div>
    </div>
</div>