<?php 
    $this->headTitle('Diamond Global Package');
    $this->headLink()->prependStylesheet($this->basePath('/assets/aim-world/css/style.css'));
?>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-6">       
            <!-- Heading -->
            <div class="heading">
               <h2 style="color: #0a3325" >Diamond Package</h2>
               <h4 style="color: #0a3325" >Serve as 5 accounts</h4>
               <p style="color: #9c9c9c" class="subheadline" >
                     
               </p>
            </div>
            <!-- Heading End -->
            <!-- Features List -->                                         
<!--            <div class="feature-block">
               <h3 style="color: #7cb28a" >Uses Nano-Thermal DiaDynamics Technology
               </h3>
               <p style=" color: #98989" >It is the first thermal patch in the world to use nano-diamonds in its delivery system where soothing heat is delivered in the molecular level.
               </p>
            </div>-->
            <!-- Features List End --> 
        </div>
        <div class="col-sm-6 col-md-6">
            <div class="wrapper">
                <img class="img-responsive third wow fadeInRight animated" src="/assets/aim-world/img/diamond-package.png" alt="" data-wow-offset="300" style="visibility: visible; animation-name: fadeInRight;">
            </div>
        </div>
    </div>
</div>