<?php $this->headTitle("Global Package"); ?>
<section id="global-package" style="height: auto; margin-top: 50px;">
    <div class="container">
        <div class="row">
            <h1>BUY NOW! <small>Options for our Global Package</small></h1>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/sapphire-package.png" alt="sapphire-package" class="img-responsive">
                    <div class="caption">
                        <h4>SAPPHIRE PACKAGE <small>(1 Account)</small></h4>
                        <h4 style="color: #0a3325">SRP: $400</h4>
                        <p>
                           Product Inclusions:
                            <ul>
                                <li>1 <a href="<?php echo $this->url('aim-world/products/i-protect'); ?>">iProtect</a> Necklace</li>
                                <li>3 <a href="<?php echo $this->url('aim-world/products/i-protect'); ?>">iProtect 24/7</a> Packets</li>
                                <li>1 <a href="<?php echo $this->url('aim-world/products/i-protect-home');?>">iProtect Home</a> Packets</li>
                                <li>
                                    5 
                                    <a href="<?php echo $this->url('aim-world/products/careleaf');?>">CareLeaf</a> 
                                    Packs
                                    <small>(20 patches per pack)</small>
                                </li>
                            </ul>
                        </p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/global-package/sapphire'); ?>" 
                               class="btn btn-warning" role="button">
                                <strong>Learn more</strong>
                            </a> 
                            <a 
                                href="<?php echo "http://shop.aimworld.today/&tracking=" . $this->layout()->aim_world_id; ?>" 
                                target="_blank"
                                class="btn btn-success" role="button">
                                <strong>Buy One</strong>
                            </a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/emerald-package.png" alt="emerald-package" class="img-responsive">
                    <div class="caption">
                        <h4>EMERALD PACKAGE <small>(3 Accounts)</small></h4>
                        <h4 style="color: #0a3325">SRP: $1370</h4>
                        <p>
                           Product Inclusions:
                            <ul>
                                <li>3 <a href="<?php echo $this->url('aim-world/products/i-protect'); ?>">iProtect</a> Necklace</li>
                                <li>9 <a href="<?php echo $this->url('aim-world/products/i-protect'); ?>">iProtect 24/7</a> Packets</li>
                                <li>4 <a href="<?php echo $this->url('aim-world/products/i-protect-home');?>">iProtect Home</a> Packets</li>
                                <li>
                                    18 
                                    <a href="<?php echo $this->url('aim-world/products/careleaf');?>">CareLeaf</a> 
                                    Packs
                                    <small>(20 patches per pack)</small>
                                </li>
                            </ul>
                        </p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/global-package/emerald'); ?>" 
                               class="btn btn-warning" role="button">
                                <strong>Learn more</strong>
                            </a> 
                            <a 
                                href="<?php echo "http://shop.aimworld.today/&tracking=" . $this->layout()->aim_world_id; ?>" 
                                target="_blank"
                                class="btn btn-success" role="button">
                                <strong>Buy One</strong>
                            </a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/diamond-package.png" alt="diamond-package" class="img-responsive">
                    <div class="caption">
                        <h4>DIAMOND PACKAGE <small>(5 Accounts)</small></h4>
                        <h4 style="color: #0a3325">SRP: $2430</h4>
                        <p>
                           Product Inclusions:
                            <ul>
                                <li>5 <a href="<?php echo $this->url('aim-world/products/i-protect'); ?>">iProtect</a> Necklace</li>
                                <li>15 <a href="<?php echo $this->url('aim-world/products/i-protect'); ?>">iProtect 24/7</a> Packets</li>
                                <li>8 <a href="<?php echo $this->url('aim-world/products/i-protect-home');?>">iProtect Home</a> Packets</li>
                                <li>
                                    32 
                                    <a href="<?php echo $this->url('aim-world/products/careleaf');?>">CareLeaf</a> 
                                    Packs
                                    <small>(20 patches per pack)</small>
                                </li>
                            </ul>
                        </p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/global-package/diamond'); ?>" 
                               class="btn btn-warning" role="button">
                                <strong>Learn more</strong>
                            </a> 
                            <a 
                                href="<?php echo "http://shop.aimworld.today/&tracking=" . $this->layout()->aim_world_id; ?>" 
                                target="_blank"
                                class="btn btn-success" role="button">
                                <strong>Buy One</strong>
                            </a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
</section>