<section style="height: auto; margin-top: 30px;" id="about">
    <div id="aim-world-info" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#aim-world-info" data-slide-to="0" class="active"></li>
          <li data-target="#aim-world-info" data-slide-to="1"></li>
          <li data-target="#aim-world-info" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="<?= $this->basePath("assets/aim-world/img/aimworld-banner.jpg") ?>" >
                <div class="carousel-caption">
                    <section>
                        <h1>AIM WORLD</h1>
                        <p>
                            New and pioneering online division of Alliance in Motion Global (known as AIM Global).
                        </p>
                        <p>
                            AIM Global is a stable company that has been around for ten (10) solid years in the industry of marketing. We received a countless number of awards for sales and product distribution from several marketing associations worldwide for hitting targets year after year.
                        </p>
                    </section>
                </div>
            </div>
            <div class="item">
                <img src="<?= $this->basePath("assets/aim-world/img/aimworld-banner.jpg") ?>">
                <div class="carousel-caption">
                    <h1>Hassle Free, Door-to-Door Delivery</h1>
                    <p>
                        Market its new line of innovative and excellent products into 200 countries. Online purchasing of products is available 24/7
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="<?= $this->basePath("assets/aim-world/img/aimworld-banner.jpg") ?>">
                <div class="carousel-caption">
                    <h1>World Class Products</h1>
                    <p>
                        Reviewed by AIM Wellness Advisory Board composed of different doctors and scientist from different continents
                    </p>
                </div>
            </div>
        </div>
    </div>        
</section>