<section id="products">
    <div class="container">
        <div class="row">
            <h1>World-class, First in the Market! <small>Innovative and excellent products</small></h1>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/pendantcase.png" alt="i-protect-24-7 pendant" class="img-responsive">
                    <div class="caption">
                        <h4>iPRO-TECT 24/7</h4>
                        <h4 style="color: #0a3325"><small>Self-Protection Technology</small></h4>
                        <p>
                            A breakthrough in the control of communicable diseases, protecting individuals round the clock.
                        </p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/i-protect'); ?>" 
                               class="btn btn-warning" role="button">
                                <strong>Learn more</strong>
                            </a> 
                            <a 
                                href="<?php echo "http://shop.aimworld.today/&tracking=" . $this->layout()->aim_world_id; ?>" 
                                target="_blank"
                                class="btn btn-success" role="button">
                                <strong>Buy One</strong>
                            </a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/careleaf.png" alt="careleaf" class="img-responsive">
                    <div class="caption">
                        <h4>CARE LEAF</h4>
                        <h4 style="color: #0a3325"><small>Thermal Relief Patch</small></h4>
                        <p>
                            The first thermal patch in the world to use nano-diamonds; delivered in the molecular level.
                        </p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/careleaf'); ?>" 
                               class="btn btn-warning" role="button">
                                <strong>Learn more</strong>
                            </a> 
                            <a 
                                href="<?php echo "http://shop.aimworld.today/&tracking=" . $this->layout()->aim_world_id; ?>" 
                                target="_blank"
                                class="btn btn-success" role="button">
                                <strong>Buy One</strong>
                            </a>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                </div>
            </div>        
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/iprotecthome.png" alt="i-protect-home" class="img-responsive">
                    <div class="caption">
                        <h4>iPRO-TECT HOME</h4>
                        <h4 style="color: #0a3325"><small>Indoor-Protection Technology</small></h4>
                        <p>
                            A revolutionary product that safe guards your home from viruses and bacteria.   
                        </p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/i-protect-home'); ?>" 
                               class="btn btn-warning" role="button">
                                <strong>Learn more</strong>
                            </a> 
                            <a 
                                href="<?php echo "http://shop.aimworld.today/&tracking=" . $this->layout()->aim_world_id; ?>" 
                                target="_blank"
                                class="btn btn-success" role="button">
                                <strong>Buy One</strong>
                            </a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <blockquote>
                <h3>
                    Our product is also bundled as Global Package, do you like to buy a Global Package?
                </h3>
                <a 
                    href="<?php echo "http://shop.aimworld.today/&tracking=" . $this->layout()->aim_world_id; ?>" 
                    target="_blank"
                    class="btn btn-success" role="button">
                    <strong>Yes, I would like to Purchase the Global Package</strong>
                </a>
                <a href="<?php echo $this->url('aim-world/products/global-package'); ?>" 
                    class="btn btn-warning" role="button">
                    <strong>Learn more about the Global Package</strong>
                </a>
            </blockquote>
        </div>
    </div>
</section>