<section id="ways-to-earn">
    <div class="container">
        <div class="row">
            <h1 class="center">Your Ways To Earn</h1>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-12">
                <h3>On-demand, Immediate Income <small>(as Daily Income)</small></h3>
                <div class="container-fluid">
                    <div class="row">
                        <h4 style="color:green; font-weight: bold">
                            RETAILING 
                            <small>Simply as Direct Selling</small>
                        </h4>
                        <p>
                            As a distributor, you can enjoy <strong>up to 25% LIFETIME discount</strong> for every product purchase.</p>
                    </div>
                    <div class="row">
                        <h4 style="color:green; font-weight: bold">
                            DIRECT REFERRAL BONUS
                        </h4>
                        <p>
                            Being a sponsor, you will get <strong>at least $25 US Dollars</strong> as direct referral bonus.
                        </p>
                        <p>
                            <small style="font-style: italic">
                                <span style="color:red">*</span> depending on the kind of package your new recruit has purchased online.
                            </small>
                        </p>
                    </div>
                    <div class="row">
                        <h4 style="color:green; font-weight: bold">MATCHED SALES BONUS <small>Using BINARY Pairing Program</small></h4>
                        <p>
                            In our <strong>BINARY PROGRAM</strong>, you need <strong><i>at least 1 in your left sales force</i></strong> and <strong><i>at least 1 in your right sales force</i></strong> to make a pair.
                        </p>
                        <p>
                            Pairing can be earned through:
                            <ol>
                                <li>
                                    <strong>Person</strong>
                                    <small>(Direct or Indirect recruit)</small>
                                    <strong>to</strong> 
                                    <strong>Person</strong>
                                    <small>(Direct or Indirect recruit)</small>
                                </li>
                                <li>Product to Product</li>
                                <li>Person <small>(Direct or Indirect recruit)</small> to Product</li>
                            </ol>
                        </p>
                        <p>
                            You will get a <strong>Matched Sales Bonus of $33 US Dollars per pair</strong>.
                        </p>
                        <p>
                            <small style="font-style: italic">
                                <span style="color:red">*</span> see the marketing plan to know about the Left or Right Sales Force - including BINARY POINTS.
                            </small>
                        </p>                         
                    </div>                    
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <h3>Product Movement Income <small>(as Monthly Income)</small></h3>                
                <div class="container-fluid">
                    <div class="row">
                        <h4 style="color:green; font-weight: bold">UNILEVEL BONUS</h4>
                        <p>
                            Enjoy a 5% Unilevel bonus as sponsor and 5% as placement.
                        </p>
                    </div>
                    <div class="row">
                        <h4 style="color:green; font-weight: bold">STAIRSTEP BONUS</h4>
                        <p>
                            Can be earned through:
                            <ol>
                                <li>Group Product Re-order and/or</li>
                                <li>Global Packages</li>
                            </ol>
                        </p>
                    </div>
                    <div class="row">
                        <h4 style="color:green; font-weight: bold">DOUBLING YOUR INCOME <small>or even <strong>TRIPLE</strong><span style="color:red">*</span></small></h4>
                        <p>
                            To get your unilevel and stairstep income, you need to purchase products equivalent to 0.3334 POINTS.
                        </p>
                        <p>
                            Tripling your income means, you need to purchase products equivalent to 0.6668 POINTS.
                        </p>
                    </div>
                    <div class="row">
                        <h4 style="color:green; font-weight: bold">ROYALTY INCOME</h4>
                        <p>
                            If any one of your downlines or directs who become a GLOBAL AMBASSADOR and you already have the same rank with him or her, you now get a ROYALTY INCOME of 2% from his group.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="divider"><br></div>
        <div class="row">
            <blockquote class="pull-right">
                <h3>
                    We truly value our Distributors so in return we provide <strong>Daily Payout</strong>, yes it's Daily!
                </h3>
                <a href="<?= $this->url('aim-world/marketing-plan')?>" class="btn btn-success btn-lg" role="button">
                    Learn more about Our Marketing Plan
                </a>
                <br>
            </blockquote>   
        </div>
        <div class="divider"><br></div>
    </div>    
</section>