<?php $this->headTitle('About AIM World'); ?>
<section  style="background-image: url('../assets/aim-world/img/aimworld-banner.jpg'); background-size: cover; background-position: center; height: 650px; background-repeat: no-repeat; margin-top: -10px;">
    <div class="container">
        <h1> Welcome to AIM World! <small>Who we are?</small> </h1>
        <p>
            Alliance in Motion Global, Inc. (known as AIM Global) is a stable company that has been around for ten (10) solid years in the industry of marketing. We received a countless number of awards for sales and product distribution from several marketing associations worldwide for hitting targets year after year.
        </p>
       <p>
           This year 2016, AIM Global is proud to introduce its newest and pioneering online division, THE AIM WORLD which would market its new line of innovative and excellent products into 200 countries. Online purchasing of products is available 24/7 with readily accessible payment scheme through credit cards. Door-to-door delivery of purchased goods shall be facilitated by AIM World wherever you may be in the globe. Indeed, it’s HASSLE-FREE!
       </p>
       <p>
           AIM World products are reviewed by AIM Wellness Advisory Board composed of different doctors and scientist from different continents.
       </p>
    </div>
</section>
<div class="divider">
    <hr>
</div>
<section id="products">
    <div class="container">
        <h2>Our Products</h2>
        <div id="container" class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/pendantcase.png" alt="i-protect-24-7 pendant" class="img-responsive">
                    <div class="caption">
                        <h3>iPRO-TECT 24/7</h3>
                        <h4 style="color: #0a3325"><small>Self-Protection Technology</small></h4>
                        <p>A breakthrough in the control of communicable diseases, protecting individuals round the clock.</p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/i-protect'); ?>" 
                               class="btn btn-success" role="button">
                                <strong>About IProtect 24/7</strong>
                            </a> 
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/careleaf.png" alt="careleaf" class="img-responsive">
                    <div class="caption">
                        <h3>CARE LEAF</h3>
                        <h4 style="color: #0a3325"><small>Thermal Relief Patch</small></h4>
                        <p>
                            Pain affects everyone, some more than others. But when it strikes, it affects our way of life…
                          Not ny more!
                        </p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/careleaf'); ?>" 
                               class="btn btn-success" role="button">
                                <strong>About CareLeaf</strong>
                            </a> 
                        </div>
                        <div class="clearfix"></div>
                    </div>

                </div>
            </div>        
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/assets/aim-world/img/iprotecthome.png" alt="i-protect-home" class="img-responsive">
                    <div class="caption">
                        <h3>iPRO-TECT HOME</h3>
                        <h4 style="color: #0a3325"><small>Indoor-Protection Technology</small></h4>
                        <p>
                            A revolutionary product that safe guards your home from viruses and bacteria.   
                        </p>
                        <div class="pull-right">
                            <a href="<?php echo $this->url('aim-world/products/i-protect-home'); ?>" 
                               class="btn btn-success" role="button">
                                <strong>About IProtect HOME</strong>
                            </a> 
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</section>
