<?php $this->headTitle('About AIM World'); ?>

<h1> 
    <strong>Welcome to AIM World!</strong> <small>Who we are?</small>
</h1>
<div class="content">
     <p>
         Alliance in Motion Global (AIM Global) is a stable company that has been around for ten (10) solid years in the industry of marketing. We received a countless number of awards for sales and product distribution from several marketing associations worldwide for hitting targets year after year.
     </p>
    <p>
        This year 2016, AIM Global is proud to introduce its newest and pioneering online division, THE AIM WORLD which would market its new line of innovative and excellent products into 200 countries. Online purchasing of products is available 24/7 with readily accessible payment scheme through credit cards. Door-to-door delivery of purchased goods shall be facilitated by AIM World wherever you may be in the globe. Indeed, it’s HASSLE-FREE!
    </p>
    <p>
        AIM World products are reviewed by AIM Wellness Advisory Board composed of different doctors and scientist from different continents.
    </p>
</div>

<div id="content">
    <h2>Our Products</h2>
    <!-- Features Section -->
    <section id="features" class="clearfix" data-scroll-index="2">

        <!-- Feature One -->
        <div class="feature">

           <div class="container">
               <div class="row">
                    <!-- Features Content -->
                    <div class="col-sm-6 col-sm-push-6 col-md-6 col-md-push-6">

                        <!-- Heading -->
                        <div class="heading">
                           <h2 style="color: #0a3325">IPROTECT 24/7</h2>
                           <p style=" color: #9c9c9c" class="subheadline" aimtranslate="">The time for Self-Protection Technology has finally come. A breakthrough in the control of communicable diseases, protecting individuals round the clock.</p>
                        </div>
                        <!-- Heading End -->

                        <!-- Features List -->                                         
                        <div class="feature-block">
                           <i class="fa fa-cogs"></i>
                           <h3 style="color: #7cb28a" aimtranslate="">Japanese Technology</h3>
                           <p style="color: #98989" aimtranslate="">After 30 years of clinical research, we come out with this amazing product that creates a barrier of protection that disintegrates unwanted particles. Patented in Japan and double-patent in the US, this product is one of a kind. 
                           </p>
                        </div>

                        <div class="feature-block">
                           <i class="fa fa-shield"></i>
                           <h3 style="color: #7cb28a" aimtranslate="">Protects What Matters Most</h3>
                           <p style="color: #98989" aimtranslate="">We spend so much in curing diseases when we can spend less with preventive intervention. 
                            Keeping our health intact assures our optimum productivity and the safety of those we love, priceless.</p>
                        </div>

                        <div class="feature-block">
                           <i class="fa fa-star-half-o"></i>
                           <h3 style="color: #7cb28a" aimtranslate="">Wearable and Fashionable</h3>
                           <p style="color: #98989" aimtranslate="">The unique design allows anyone to wear IPROTECT anytime and anywhere. The flower of life is a symbol for balance, serenity and harmony, a life that is secured from airborne diseases.
                           </p>
                        </div>
                        <!-- Features List End -->

                    </div>

                   <div class="col-sm-6 col-sm-pull-6 col-md-6 col-md-pull-6">       

                        <div class="wrapper">                            
                          <img class="img-responsive first wow fadeInLeft animated" style="margin-left: 80px !important; visibility: visible; animation-name: fadeInLeft;" src="assets/aim-world/img/pendant.png" alt="" data-wow-offset="200">   
<!--                          <img class="img-responsive second wow fadeInLeft animated" src="/assets/aim-world/img/pendantcase.png" alt="" data-wow-delay="0.5s" data-wow-offset="200" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInLeft;">-->
                          </div>                                 
                    </div>
                    <!-- Features Content End -->
               </div><!-- .row End -->
            </div><!-- .container End -->
        </div>
        <!-- Feature One End -->

        <!-- Feature Two -->
        <div class="feature">
            <div class="container">
               <div class="row">
                    <!-- Features Content -->
                    <div class="col-sm-6 col-md-6">       
                          <!-- Heading -->
                          <div class="heading">
                             <h2 style="color: #0a3325" aimtranslate="">CARE LEAF</h2>
                             <h4 style="color: #0a3325" aimtranslate="">Thermal Relief Patch</h4>
                             <p style="color: #9c9c9c" class="subheadline" aimtranslate="">
                                   Pain affects everyone, some more than others. But when it strikes, it affects our way of life…
                                   Not ny more!
                             </p>
                          </div>
                          <!-- Heading End -->

                          <!-- Features List -->                                         
                          <div class="feature-block">
                             <i class="fa fa-cog"></i>
                             <h3 style="color: #7cb28a" aimtranslate="">Uses Nano-Thermal DiaDynamics Technology
                             </h3>
                             <p style=" color: #98989" aimtranslate="">It is the first thermal patch in the world to use nano-diamonds in its delivery system where soothing heat is delivered in the molecular level.   

                             </p>
                          </div>

                           <div class="feature-block">
                             <i class="fa fa-leaf"></i>
                             <h3 style="color: #7cb28a" aimtranslate="">All Natural</h3>
                             <p style=" color: #98989" aimtranslate="">Nine natural ingredients are infused in microlayers, each known and used for decades to relieve pain.
                             No synthetic substances were used in this great alternative to mainstream medicine. All natural, no side effects, just immediate soothing heat.</p>
                          </div>

                           <div class="feature-block">
                             <i class="fa fa-heart"></i>
                             <h3 style="color: #7cb28a" aimtranslate="">Everyday Care</h3>
                             <p style=" color: #98989" aimtranslate="">Be free from the limitations that you’ve had for years and again start doing the things you’ve been wanting to do.
                              Whenever you feel musculoskeletal pain, you can use these thermal patches, even everyday! Pain away! </p>
                          </div>
                          <!-- Features List End -->                          

                    </div>

                    <div class="col-sm-6 col-md-6">                                    
                          <img class="img-responsive third wow fadeInRight animated" src="/assets/aim-world/img/careleaf.png" alt="" data-wow-offset="300" style="visibility: visible; animation-name: fadeInRight;">   
                          <img class="img-responsive fourth wow fadeInRight animated" src="/assets/aim-world/img/careleaf.png" alt="" data-wow-delay="0.5s" data-wow-offset="300" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInRight;">                                   
                    </div>
                    <!-- Features Content End -->
               </div><!-- .row End -->
            </div><!-- .container End -->
        </div>
        
        <!-- Feature Two End -->
        <div class="feature" >
                 <div class="container">
                    <div class="row">
                        <!-- Features Content -->
                        <div class="col-sm-6 col-sm-push-6 col-md-6 col-md-push-6">
                              <!-- Heading -->
                              <div class="heading">
                                 <h2 style="color: #0a3325">IPROTECT HOME</h2>
                                 <p style=" color: #9c9c9c" class="subheadline" aimtranslate="">A revolutionary product that safe guards your home from viruses and bacteria.
                     </p>
                              </div>
                              <!-- Heading End -->

                              <!-- Features List -->                                         
                              <div class="feature-block">
                                 <i class="fa fa-stethoscope"></i>
                                 <h3 style="color: #7cb28a" aimtranslate="">Doctor Formulated</h3>
                                 <p style="color: #989898" aimtranslate="">Backed up by clinical research and tested to kill harmful viruses and bacteria indoors.
                     </p>
                              </div>

                              <div class="feature-block">
                                 <i class="fa fa-shield"></i>
                                 <h3 style="color: #7cb28a" aimtranslate="">Designed for various application
                     </h3>
                                 <p style="color: #989898" aimtranslate="">Place it in your child’s playroom, in your office desk or inside the refrigerator – protection starts immediately.
                     </p>
                              </div>

                              <div class="feature-block">
                                 <i class="fa fa-star-half-o"></i>
                                 <h3 style="color: #7cb28a" aimtranslate="">Preventive Intervention</h3>
                                 <p style="color: #989898" aimtranslate="">
                     Increase your defense against airborne infection and boost immunity inside your home.
                     </p>
                              </div>
                              <!-- Features List End -->

                        </div>

                       <div class="col-sm-6 col-sm-pull-6 col-md-6 col-md-pull-6">                                 
                              <img class="img-responsive first wow fadeInLeft animated" src="/assets/aim-world/img/iprotecthome.png" alt="" data-wow-offset="300" style="visibility: visible; animation-name: fadeInLeft;">   
<!--                              <img class="img-responsive second wow fadeInLeft animated" src="/assets/aim-world/img/iprotecthome.png" alt="" data-wow-delay="0.5s" data-wow-offset="300" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInLeft;">                                 -->
                        </div>
                        <!-- Features Content End -->
                    </div><!-- .row End -->
                 </div><!-- .container End -->
        </div>
    </section>
</div>