<?php $this->headTitle('Careleaf thermal patch'); ?>
<div class="row">
    <div class="feature">
            <div class="container">
               <div class="row">
                    <!-- Features Content -->
                    <div class="col-sm-6 col-md-6">       
                        <!-- Heading -->
                        <div class="heading">
                           <h2 style="color: #0a3325" >CARE LEAF</h2>
                           <h4 style="color: #0a3325" >Thermal Relief Patch</h4>
                           <p style="color: #9c9c9c" class="subheadline" >
                                 Pain affects everyone, some more than others. But when it strikes, it affects our way of life…
                                 Not ny more!
                           </p>
                        </div>
                        <!-- Heading End -->
                        <!-- Features List -->                                         
                        <div class="feature-block">
                           <h3 style="color: #7cb28a" >Uses Nano-Thermal DiaDynamics Technology
                           </h3>
                           <p style=" color: #98989" >It is the first thermal patch in the world to use nano-diamonds in its delivery system where soothing heat is delivered in the molecular level.
                           </p>
                        </div>

                         <div class="feature-block">
                           <h3 style="color: #7cb28a" >All Natural</h3>
                           <p style=" color: #98989" >Nine natural ingredients are infused in microlayers, each known and used for decades to relieve pain.
                           No synthetic substances were used in this great alternative to mainstream medicine. All natural, no side effects, just immediate soothing heat.</p>
                        </div>
                        
                        <div class="feature-block">
                           <h3 style="color: #7cb28a" >Everyday Care</h3>
                           <p style=" color: #98989" >Be free from the limitations that you’ve had for years and again start doing the things you’ve been wanting to do.
                            Whenever you feel musculoskeletal pain, you can use these thermal patches, even everyday! Pain away! </p>
                        </div>
                        <!-- Features List End --> 
                    </div>

                    <div class="col-sm-6 col-md-6">
                        <div class="wrapper">
                            <img class="img-responsive third wow fadeInRight animated" src="/assets/aim-world/img/careleaf.png" alt="" data-wow-offset="300" style="visibility: visible; animation-name: fadeInRight;">
                        </div>
                    </div>
                    <!-- Features Content End -->
               </div><!-- .row End -->
            </div><!-- .container End -->
        </div>
</div>
<div class="row">
    <div class="container">
        <div class="row">
            <h1>How does it work?</h1>
        </div>
        <div class="row">
            <h1>What are the contents?</h1>
        </div>
    </div>
</div>