<?php $this->headTitle('i-Protect 24/7'); ?>
<div class="row">
    <div class="feature">
           <div class="container">
               <div class="row">
                    <!-- Features Content -->
                    <div class="col-sm-6 col-sm-push-6 col-md-6 col-md-push-6">
                        <!-- Heading -->
                        <div class="heading">
                            <h2 style="color: #0a3325">IPROTECT 24/7</h2>
                            <p style=" color: #9c9c9c" class="subheadline" >The time for Self-Protection Technology has finally come. A breakthrough in the control of communicable diseases, protecting individuals round the clock.</p>
                        </div>
                        <!-- Heading End -->
                        
                        <!-- Features List -->                                         
                        <div class="feature-block">                           
                            <h3 style="color: #7cb28a" >Japanese Technology</h3>
                            <p style="color: #98989" >After 30 years of clinical research, we come out with this amazing product that creates a barrier of protection that disintegrates unwanted particles. Patented in Japan and double-patent in the US, this product is one of a kind. 
                            </p>
                        </div>

                        <div class="feature-block">
                            <h3 style="color: #7cb28a" >Protects What Matters Most</h3>
                            <p style="color: #98989" >We spend so much in curing diseases when we can spend less with preventive intervention. 
                             Keeping our health intact assures our optimum productivity and the safety of those we love, priceless.</p>
                        </div>

                        <div class="feature-block">
                           <h3 style="color: #7cb28a" >Wearable and Fashionable</h3>
                           <p style="color: #98989" >The unique design allows anyone to wear IPROTECT anytime and anywhere. The flower of life is a symbol for balance, serenity and harmony, a life that is secured from airborne diseases.
                           </p>
                        </div>
                        <!-- Features List End -->
                    </div>

                   <div class="col-sm-6 col-sm-pull-6 col-md-6 col-md-pull-6"> 
                        <div class="wrapper">                            
                             <img class="img-responsive first wow fadeInLeft animated" style="margin-left: 80px !important; visibility: visible; animation-name: fadeInLeft;" src="/assets/aim-world/img/pendant.png" alt="" data-wow-offset="200">
                         </div> 
                        
                    </div>
                    <!-- Features Content End -->
               </div><!-- .row End -->
            </div><!-- .container End -->
        </div>
</div>
<div class="row">
    <div class="container">
        <div class="row">
            <h1>How does it work?</h1>
        </div>
        <div class="row">
            <h1>What are the contents?</h1>
        </div>
    </div>
</div>