<?php $this->headTitle('i-Protect Home'); ?>
<div class="row">
    <div class="feature" >
                 <div class="container">
                    <div class="row">
                        <!-- Features Content -->
                        <div class="col-sm-6 col-sm-push-6 col-md-6 col-md-push-6">
                            <!-- Heading -->
                            <div class="heading">
                                <h2 style="color: #0a3325">IPROTECT HOME</h2>
                                <p style=" color: #9c9c9c" class="subheadline" >
                                    A revolutionary product that safe guards your home from viruses and bacteria.    
                                </p>
                            </div>
                            <!-- Heading End -->
                            <!-- Features List -->                                         
                            <div class="feature-block">
                                <h3 style="color: #7cb28a" >Doctor Formulated</h3>
                                <p style="color: #989898" >
                                    Backed up by clinical research and tested to kill harmful viruses and bacteria indoors.
                                </p>
                            </div>

                            <div class="feature-block">
                                <h3 style="color: #7cb28a" >Designed for various application</h3>
                                <p style="color: #989898" >
                                    Place it in your child’s playroom, in your office desk or inside the refrigerator – protection starts immediately.
                                </p>
                            </div>
                            <div class="feature-block">
                                <h3 style="color: #7cb28a" >Preventive Intervention</h3>
                                <p style="color: #989898" >
                                    Increase your defense against airborne infection and boost immunity inside your home.
                                </p>
                            </div>
                            <!-- Features List End -->                            
                        </div>
                       <div class="col-sm-6 col-sm-pull-6 col-md-6 col-md-pull-6">
                           <div class="wrapper">
                               <img class="img-responsive first wow fadeInLeft animated" src="/assets/aim-world/img/iprotecthome.png" alt="" data-wow-offset="300" style="visibility: visible; animation-name: fadeInLeft;">
                           </div>
                        </div>
                        <!-- Features Content End -->
                    </div><!-- .row End -->
                 </div><!-- .container End -->
        </div>
</div>
<div class="row">
    <div class="container">
        <div class="row">
            <h1>How does it work?</h1>
        </div>
        <div class="row">
            <h1>What are the contents?</h1>
        </div>
    </div>
</div>